//CAPTURES THE AVERAGE OF DAYS BETWEEN WHEN A REPORT WAS SUBMITTED AND WHEN IT WAS APPROVED. APPROVAL DATE IS DEFINED WHERE THE EXPENSEREPORTLINEITEM HAS AN APPROVED STATUS AND THE MAXIMUM/LAST UPDATE IS CAPTURED//
SET VAR_START_DATE ='01-JAN-2019';
SET VAR_END_DATE = GETDATE();

SELECT YEAR, AVG(AVG_DATEF) FROM
((SELECT BU_REGION, YEAR,  AVG(DATEDIFF(DAY,SUBMITDAY, APPROVALDAY) +1)  AS AVG_DATEF FROM 
((SELECT 
  'US' AS BU_REGION
, YEAR (h.SUBMITDATE) AS YEAR
, s.EXPENSEREPORTLINEITEMID
, MIN(h.SUBMITDATE) AS SUBMITDAY
, MAX(S.UPDATEDATE) AS APPROVALDAY


FROM "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEMSTEP" S
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CUSTOMERDATA" CD

WHERE H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
AND L.EXPENSEREPORTLINEITEMID = S.EXPENSEREPORTLINEITEMID
AND S.CUSTOMERID = C.CUSTOMERID
AND C.CUSTOMERID = CD.CUSTOMERID 
AND h.SUBMITDATE>= $var_start_date and h.SUBMITDATE<= $var_end_date
AND LOWER(CD.STATUSIMPL) LIKE '%live%'
and s.STATUSAPPROVED = 'APP'
AND H._FIVETRAN_DELETED = 'FALSE' AND L._FIVETRAN_DELETED = 'FALSE' AND S._FIVETRAN_DELETED = 'FALSE'

GROUP BY YEAR,s.EXPENSEREPORTLINEITEMID
ORDER BY YEAR
)

UNION ALL

(SELECT 
  'US' AS BU_REGION
, YEAR (h.SUBMITDATE) AS YEAR
, s.EXPENSEREPORTLINEITEMID
, MIN(h.SUBMITDATE) AS SUBMITDAY
, MAX(S.UPDATEDATE) AS APPROVALDAY


FROM "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEMSTEP" S
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_CUSTOMERDATA" CD

WHERE H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
AND L.EXPENSEREPORTLINEITEMID = S.EXPENSEREPORTLINEITEMID
AND S.CUSTOMERID = C.CUSTOMERID
AND C.CUSTOMERID = CD.CUSTOMERID 
AND h.SUBMITDATE>= $var_start_date and h.SUBMITDATE<= $var_end_date
AND LOWER(CD.STATUSIMPL) LIKE '%live%'
and s.STATUSAPPROVED = 'APP'
AND H._FIVETRAN_DELETED = 'FALSE' AND L._FIVETRAN_DELETED = 'FALSE' AND S._FIVETRAN_DELETED = 'FALSE'

GROUP BY YEAR,s.EXPENSEREPORTLINEITEMID
ORDER BY YEAR
)
UNION ALL
 (SELECT 
  'US' AS BU_REGION
, YEAR (h.SUBMITDATE) AS YEAR
, s.EXPENSEREPORTLINEITEMID
, MIN(h.SUBMITDATE) AS SUBMITDAY
, MAX(S.UPDATEDATE) AS APPROVALDAY


FROM "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEMSTEP" S
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_CUSTOMERDATA" CD

WHERE H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
AND L.EXPENSEREPORTLINEITEMID = S.EXPENSEREPORTLINEITEMID
AND S.CUSTOMERID = C.CUSTOMERID
AND C.CUSTOMERID = CD.CUSTOMERID 
AND h.SUBMITDATE>= $var_start_date and h.SUBMITDATE<= $var_end_date
AND LOWER(CD.STATUSIMPL) LIKE '%live%'
and s.STATUSAPPROVED = 'APP'
AND H._FIVETRAN_DELETED = 'FALSE' AND L._FIVETRAN_DELETED = 'FALSE' AND S._FIVETRAN_DELETED = 'FALSE'

GROUP BY YEAR,s.EXPENSEREPORTLINEITEMID
ORDER BY YEAR))
GROUP BY BU_REGION,YEAR
ORDER BY YEAR))

GROUP BY YEAR
ORDER BY YEAR