//GRAB DISTINCT COUNT OF MONTHLY HOARDERS REPORTS

select 'MONTHLY_HOARDERS' AS TOTAL_REPORTS ,(sum(reports)) AS COUNT from

//GRAB DISTINCT COUNT OF MONTHLY HOARDERS
//MONTHLY HOARDERS IS DEFINED WHERE THE EARLIEST EXPENSE DATE ACROSS ALL LINE ITEMS IS 25 DAYS OR MORE BEFORE THE SUBMIT DATE, HAS >=3 ITEMS IN REPORT, AND REPORT CREATE DATE<3 DAYS FROM REPOR SUBMISSION

--lect 'MONTHLY_HOARDERS' AS TOTAL_USERS ,(count(Distinct(PersonID))) AS COUNT from

((select
'C1' AS CLUSTER_LOCATION
,COUNT(H.EXPENSEREPORTHEADERID) as reports
, H.PERSONID
, concat(P.FIRSTNAME, P.LASTNAME,' ') as CUSTOMER_NAME
, H.CUSTOMERID
, C.NAME
, H.SUBMITDATE
, MIN(TRANSACTIONDATE) as mindate
, DATEDIFF(DAYS,MIN(TRANSACTIONDATE),SUBMITDATE) AS DIFF
, COUNT(L.EXPENSEREPORTLINEITEMID) AS EXPENSECOUNT
from "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
join "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_PERSON" P on P.PERSONID = H.PERSONID
join "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C on C.CUSTOMERID = H.CUSTOMERID
join "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L ON H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
where SUBMITDATE between (LAST_DAY(SUBMITDATE) - interval '3 day') and LAST_DAY(SUBMITDATE)
and YEAR(SUBMITDATE) =2021
and H._FIVETRAN_DELETED = FALSE and P._FIVETRAN_DELETED = FALSE and C._FIVETRAN_DELETED = FALSE
AND P.PERSONSTATUSID = 2
and h.STATUSID IN (3,5)
and P.PERSONID not in 
(select PERSONID from "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
 join "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L ON H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
where 
SUBMITDATE not between (LAST_DAY(SUBMITDATE) - interval '3 day') and LAST_DAY(SUBMITDATE)
AND YEAR(SUBMITDATE) = 2021
group by H.CustomerID,H. PersonID, H.ExpenseReportHeaderID
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID) 
group by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID,P.FIRSTNAME, P.LASTNAME,C.NAME, H.SUBMITDATE HAVING EXPENSECOUNT>=3 AND DIFF>=25
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID)

UNION ALL

(select
'C2' AS CLUSTER_LOCATION
,COUNT(H.EXPENSEREPORTHEADERID) as reports
, H.PERSONID
, concat(P.FIRSTNAME, P.LASTNAME,' ') as CUSTOMER_NAME
, H.CUSTOMERID
, C.NAME
, H.SUBMITDATE
, MIN(TRANSACTIONDATE) as mindate
, DATEDIFF(DAYS,MIN(TRANSACTIONDATE),SUBMITDATE) AS DIFF
, COUNT(L.EXPENSEREPORTLINEITEMID) AS EXPENSECOUNT
from "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
join "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_PERSON" P on P.PERSONID = H.PERSONID
join "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C on C.CUSTOMERID = H.CUSTOMERID
join "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L ON H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
where SUBMITDATE between (LAST_DAY(SUBMITDATE) - interval '3 day') and LAST_DAY(SUBMITDATE)
and YEAR(SUBMITDATE) =2021
and H._FIVETRAN_DELETED = FALSE and P._FIVETRAN_DELETED = FALSE and C._FIVETRAN_DELETED = FALSE
AND P.PERSONSTATUSID = 2
and h.STATUSID IN (3,5)
and P.PERSONID not in 
(select PERSONID from "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
where 
SUBMITDATE not between (LAST_DAY(SUBMITDATE) - interval '3 day') and LAST_DAY(SUBMITDATE)
AND YEAR(SUBMITDATE) = 2021
group by H.CustomerID,H. PersonID, H.ExpenseReportHeaderID
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID) 
group by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID,P.FIRSTNAME, P.LASTNAME,C.NAME, H.SUBMITDATE HAVING EXPENSECOUNT>=3 AND DIFF>=25
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID)
UNION ALL

(select
'C7' AS CLUSTER_LOCATION
,COUNT(H.EXPENSEREPORTHEADERID) as reports
, H.PERSONID
, concat(P.FIRSTNAME, P.LASTNAME,' ') as CUSTOMER_NAME
, H.CUSTOMERID
, C.NAME
, H.SUBMITDATE
, MIN(TRANSACTIONDATE) as mindate
, DATEDIFF(DAYS,MIN(TRANSACTIONDATE),SUBMITDATE) AS DIFF
, COUNT(L.EXPENSEREPORTLINEITEMID) AS EXPENSECOUNT
from "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
join "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_PERSON" P on P.PERSONID = H.PERSONID
join "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C on C.CUSTOMERID = H.CUSTOMERID
join "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L ON H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
where SUBMITDATE between (LAST_DAY(SUBMITDATE) - interval '3 day') and LAST_DAY(SUBMITDATE)
and YEAR(SUBMITDATE) =2021
and H._FIVETRAN_DELETED = FALSE and P._FIVETRAN_DELETED = FALSE and C._FIVETRAN_DELETED = FALSE
AND P.PERSONSTATUSID = 2
and h.STATUSID IN (3,5)
and P.PERSONID not in 
(select PERSONID from "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
where 
SUBMITDATE not between (LAST_DAY(SUBMITDATE) - interval '3 day') and LAST_DAY(SUBMITDATE)
AND YEAR(SUBMITDATE) = 2021
group by H.CustomerID,H. PersonID, H.ExpenseReportHeaderID
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID) 
group by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID,P.FIRSTNAME, P.LASTNAME,C.NAME, H.SUBMITDATE HAVING EXPENSECOUNT>=3 AND DIFF>=25
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID))