//GRAB DISTINCT COUNT OF MONTHLY HOARDERS REPORTS

select 'procrastinators' AS TOTAL_USERS ,(count(Distinct(PersonID))) AS COUNT from


((select
'C1' AS CLUSTER_LOCATION
,COUNT (H.EXPENSEREPORTHEADERID) AS REPORTS
, H.PERSONID
, concat(P.FIRSTNAME, P.LASTNAME,' ') as CUSTOMER_NAME
, H.CUSTOMERID
, C.NAME
, H.SUBMITDATE
, MIN(TRANSACTIONDATE) as mindate
, DATEDIFF(DAYS,MIN(TRANSACTIONDATE),SUBMITDATE) AS DIFF
, COUNT(L.EXPENSEREPORTLINEITEMID) AS EXPENSECOUNT
from "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
join "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_PERSON" P on P.PERSONID = H.PERSONID
join "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C on C.CUSTOMERID = H.CUSTOMERID
join "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L ON H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
where YEAR(SUBMITDATE) =2019
and H._FIVETRAN_DELETED = FALSE and P._FIVETRAN_DELETED = FALSE and C._FIVETRAN_DELETED = FALSE
AND P.PERSONSTATUSID = 2
and h.STATUSID IN (3,5)
group by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID,P.FIRSTNAME, P.LASTNAME,C.NAME, H.SUBMITDATE HAVING DIFF BETWEEN 14 AND 25
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID)
 
UNION ALL

(select
'C2' AS CLUSTER_LOCATION
,COUNT (H.EXPENSEREPORTHEADERID) AS REPORTS
, H.PERSONID
, concat(P.FIRSTNAME, P.LASTNAME,' ') as CUSTOMER_NAME
, H.CUSTOMERID
, C.NAME
, H.SUBMITDATE
, MIN(TRANSACTIONDATE) as mindate
, DATEDIFF(DAYS,MIN(TRANSACTIONDATE),SUBMITDATE) AS DIFF
, COUNT(L.EXPENSEREPORTLINEITEMID) AS EXPENSECOUNT
from "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
join "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_PERSON" P on P.PERSONID = H.PERSONID
join "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C on C.CUSTOMERID = H.CUSTOMERID
join "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L ON H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
where YEAR(SUBMITDATE) =2019
and H._FIVETRAN_DELETED = FALSE and P._FIVETRAN_DELETED = FALSE and C._FIVETRAN_DELETED = FALSE
AND P.PERSONSTATUSID = 2
and h.STATUSID IN (3,5)
group by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID,P.FIRSTNAME, P.LASTNAME,C.NAME, H.SUBMITDATE HAVING DIFF BETWEEN 14 AND 25
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID)
 
UNION ALL

(select
'C7' AS CLUSTER_LOCATION
,COUNT (H.EXPENSEREPORTHEADERID) AS REPORTS
, H.PERSONID
, concat(P.FIRSTNAME, P.LASTNAME,' ') as CUSTOMER_NAME
, H.CUSTOMERID
, C.NAME
, H.SUBMITDATE
, MIN(TRANSACTIONDATE) as mindate
, DATEDIFF(DAYS,MIN(TRANSACTIONDATE),SUBMITDATE) AS DIFF
, COUNT(L.EXPENSEREPORTLINEITEMID) AS EXPENSECOUNT
from "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H 
join "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_PERSON" P on P.PERSONID = H.PERSONID
join "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C on C.CUSTOMERID = H.CUSTOMERID
join "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L ON H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
where YEAR(SUBMITDATE) =2019
and H._FIVETRAN_DELETED = FALSE and P._FIVETRAN_DELETED = FALSE and C._FIVETRAN_DELETED = FALSE
AND P.PERSONSTATUSID = 2
and h.STATUSID IN (3,5)
group by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID,P.FIRSTNAME, P.LASTNAME,C.NAME, H.SUBMITDATE HAVING DIFF BETWEEN 14 AND 25
order by H.CustomerID, H.PersonID, H.ExpenseReportHeaderID))