//transaction to report 

SET VAR_START_DATE ='01-JAN-2019';
SET VAR_END_DATE = '31-DEC-2021';

SELECT YEAR,AVG(DATE_DIFF) FROM 
((SELECT 
 YEAR (T.CREATEDATE) AS YEAR
, AVG (DATEDIFF(DAY,T.CREATEDATE, H.CREATEDATE) +1)  AS DATE_DIFF

FROM "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_EXPENSETRANSACTION"  T 
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CUSTOMERDATA" CD

WHERE H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
AND L.EXPENSETRANSACTIONID = T.EXPENSETRANSACTIONID
AND T.CUSTOMERID = C.CUSTOMERID
AND C.CUSTOMERID = CD.CUSTOMERID
AND lower(CD.STATUSIMPL) like '%live%'
AND T.CREATEDATE>= $var_start_date and T.CREATEDATE<= $var_end_date
AND H._FIVETRAN_DELETED = 'FALSE' AND L._FIVETRAN_DELETED = 'FALSE' AND T._FIVETRAN_DELETED = 'FALSE'

GROUP BY YEAR
ORDER BY YEAR)

UNION ALL 

(SELECT 
 YEAR (T.CREATEDATE) AS YEAR
, AVG (DATEDIFF(DAY,T.CREATEDATE, H.CREATEDATE) +1)  AS DATE_DIFF

FROM "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_EXPENSETRANSACTION"  T 
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C
, "BRONZE_CR"."CR_C2_PROD_CHROME_EXPENSE"."TBL_CUSTOMERDATA" CD

WHERE H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
AND L.EXPENSETRANSACTIONID = T.EXPENSETRANSACTIONID
AND T.CUSTOMERID = C.CUSTOMERID
AND C.CUSTOMERID = CD.CUSTOMERID
AND lower(CD.STATUSIMPL) like '%live%'
AND T.CREATEDATE>= $var_start_date and T.CREATEDATE<= $var_end_date
AND H._FIVETRAN_DELETED = 'FALSE' AND L._FIVETRAN_DELETED = 'FALSE' AND T._FIVETRAN_DELETED = 'FALSE'

GROUP BY YEAR
ORDER BY YEAR)

UNION ALL 
 
(SELECT 
 YEAR (T.CREATEDATE) AS YEAR
, AVG (DATEDIFF(DAY,T.CREATEDATE, H.CREATEDATE) +1)  AS DATE_DIFF

FROM "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTHEADER" H
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSEREPORTLINEITEM" L
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_EXPENSETRANSACTION"  T 
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" C
, "BRONZE_CR"."CR_C7_PROD_CHROME_EXPENSE"."TBL_CUSTOMERDATA" CD

WHERE H.EXPENSEREPORTHEADERID = L.EXPENSEREPORTHEADERID
AND L.EXPENSETRANSACTIONID = T.EXPENSETRANSACTIONID
AND T.CUSTOMERID = C.CUSTOMERID
AND C.CUSTOMERID = CD.CUSTOMERID
AND lower(CD.STATUSIMPL) like '%live%'
AND T.CREATEDATE>= $var_start_date and T.CREATEDATE<= $var_end_date
AND H._FIVETRAN_DELETED = 'FALSE' AND L._FIVETRAN_DELETED = 'FALSE' AND T._FIVETRAN_DELETED = 'FALSE'

GROUP BY YEAR
ORDER BY YEAR))
GROUP BY YEAR
ORDER BY YEAR